### ISSUE TITLE
Suggestion: Remove "gh-pages" branch

### ISSUE THREAD

**Issue by DavidLemayian** [matthewtrask/matthewtrask.github.io#2]
Just a small suggestion; remove the `gh-pages` branch and keep the `master` as default. That way no need to keep them synced as everything goes direct to being published on Github pages. :)

**Comment by rocketpastsix** [comment]
Master isnt needed? I didnt know that. So GH-Pages will still push content based on the CNAME file?

**Comment by DavidLemayian** [comment]
@rocketpastsix So just did a bit more digging and looks like yours is a ["User Page"](https://help.github.com/articles/user-organization-and-project-pages/) and therefore builds from the `master` branch. In which case the `gh-pages` branch is the one you don't need. Also see [docs on CNAME adding](https://help.github.com/articles/adding-a-cname-file-to-your-repository/).
